apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "vllm.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
