apiVersion: v1
kind: Service
metadata:
  name: general-sim-api
  namespace: general-sim
  labels:
    app: general-sim-api
    app.kubernetes.io/name: general-sim-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: general-sim
spec:
  selector:
    app: general-sim-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  type: ClusterIP
