apiVersion: v1
kind: Service
metadata:
  name: llamastack
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llamastack.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "llamastack.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8321
      targetPort: 8321
  type: ClusterIP
