apiVersion: v1
kind: Namespace
metadata:
  name: general-sim
  labels:
    app.kubernetes.io/part-of: general-sim
    # Required if you use the Red Hat OpenShift Service Mesh or Network Policies
    # that rely on namespace labels.
